[package]
name = "tinylevel"
version = "0.1.0"
edition = "2021"

[dependencies]
sqlx = { version = "0.7.0", features = ["runtime-tokio", "sqlite", "macros"] }
tokio = { version = "1", features = ["rt-multi-thread", "macros", "signal"] }
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
twilight-gateway = "0.15"
twilight-model = "0.15"
twilight-http = "0.15"
parking_lot = "0.12"
dotenvy = "0.15"
tracing = "0.1"
ahash = "0.8"