services:
  bot:
    build: .
    image: ghcr.io/randomairborne/tinylevel:latest
    pull_policy: always
    volumes:
      - ${PWD}/data/:/data/
    env_file:
      - .env
    environment:
      DATABASE_URL: sqlite:///data/tinylevel.db
