name: PR check
on:
  pull_request:
  workflow_dispatch:
  workflow_call:

env:
  SQLX_OFFLINE: true

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code into the proper directory
        uses: actions/checkout@v4

      - name: Install cargo
        uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt, clippy

      - name: Cache rust
        uses: Swatinem/rust-cache@v2

      - name: Check formatting
        run: cargo fmt --check

      - name: Check build
        run: cargo clippy

      - name: Run tests
        run: cargo test
